version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - "main"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - .env

  etl_pipeline:
    build: .
    depends_on:
      - db
    networks:
      - "main"
    volumes:
      - .:/app/
    command: python src/news_etl.py
    env_file:
      - .env    
networks:
  main:    